-- MySQL Script generated by MySQL Workbench
-- lun 03 ago 2020 22:17:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `DPI` VARCHAR(13) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Tipo` INT NOT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT 0,
  PRIMARY KEY (`DPI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `Codigo` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `Telefono1` VARCHAR(8) NOT NULL,
  `Telefono2` VARCHAR(8) NULL,
  `Correo` VARCHAR(30) NULL,
  `Horario` VARCHAR(60) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiempoTraslado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiempoTraslado` (
  `CodigoTienda1` VARCHAR(10) NOT NULL,
  `CodigoTienda2` VARCHAR(10) NOT NULL,
  `Tiempo` INT NOT NULL,
  PRIMARY KEY (`CodigoTienda1`, `CodigoTienda2`),
  INDEX `FK_Tienda2_Codigo_idx` (`CodigoTienda2` ASC) VISIBLE,
  CONSTRAINT `FK_Tienda1_Codigo`
    FOREIGN KEY (`CodigoTienda1`)
    REFERENCES `mydb`.`Tienda` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Tienda2_Codigo`
    FOREIGN KEY (`CodigoTienda2`)
    REFERENCES `mydb`.`Tienda` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Nit` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(8) NOT NULL,
  `CUI` VARCHAR(13) NULL,
  `CreditoCompra` FLOAT NULL,
  `Correo` VARCHAR(45) NULL,
  `Direccion` VARCHAR(50) NULL,
  PRIMARY KEY (`Nit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `NitCliente` VARCHAR(10) NOT NULL,
  `CodigoTienda` VARCHAR(10) NOT NULL,
  `Fecha` DATE NOT NULL,
  `PorcentajeEfectivo` FLOAT NULL,
  `PorcentajeCredito` FLOAT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Tienda_Codigo_idx` (`CodigoTienda` ASC) VISIBLE,
  INDEX `FK_Cliente_Nit_idx` (`NitCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Tienda_Codigo`
    FOREIGN KEY (`CodigoTienda`)
    REFERENCES `mydb`.`Tienda` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Cliente_Nit`
    FOREIGN KEY (`NitCliente`)
    REFERENCES `mydb`.`Cliente` (`Nit`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Fabricante` VARCHAR(30) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Descripcion` VARCHAR(75) NULL,
  `Garantia` INT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoVenta` (
  `IdVenta` INT NOT NULL,
  `CodigoProducto` VARCHAR(15) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`IdVenta`, `CodigoProducto`),
  INDEX `FK_Producto_Codigo_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `FK_Venta_Id`
    FOREIGN KEY (`IdVenta`)
    REFERENCES `mydb`.`Venta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Producto_Codigo`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `mydb`.`Producto` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ExistenciaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ExistenciaProducto` (
  `CodigoTienda` VARCHAR(10) NOT NULL,
  `CodigoProducto` VARCHAR(15) NOT NULL,
  `Existencias` INT NOT NULL,
  PRIMARY KEY (`CodigoTienda`, `CodigoProducto`),
  INDEX `FK_Producto_Codigo_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `FK_Tienda_Codigo`
    FOREIGN KEY (`CodigoTienda`)
    REFERENCES `mydb`.`Tienda` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Producto_Codigo`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `mydb`.`Producto` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `CodigoPedido` VARCHAR(15) NOT NULL,
  `NitCliente` VARCHAR(10) NOT NULL,
  `CodigoTiendaOrigen` VARCHAR(10) NOT NULL,
  `CodigoTiendaDestino` VARCHAR(10) NOT NULL,
  `TiempoTraslado` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `FechaVerificacion` DATE NULL,
  `FechaRetiro` DATE NULL,
  `PorcentajeEfectivo` FLOAT NULL,
  `PorcentajeCredito` FLOAT NULL,
  `PorcentajePagado` FLOAT NOT NULL,
  `Estado` INT NULL DEFAULT 0,
  PRIMARY KEY (`CodigoPedido`),
  INDEX `FK_Cliente_Nit_idx` (`NitCliente` ASC) VISIBLE,
  INDEX `FK_TiendaO_Codigo_idx` (`CodigoTiendaOrigen` ASC) VISIBLE,
  INDEX `FK_TiendaD_Codigo_idx` (`CodigoTiendaDestino` ASC) VISIBLE,
  CONSTRAINT `FK_Cliente_Nit`
    FOREIGN KEY (`NitCliente`)
    REFERENCES `mydb`.`Cliente` (`Nit`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TiendaO_Codigo`
    FOREIGN KEY (`CodigoTiendaOrigen`)
    REFERENCES `mydb`.`Tienda` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TiendaD_Codigo`
    FOREIGN KEY (`CodigoTiendaDestino`)
    REFERENCES `mydb`.`Tienda` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoPedido` (
  `CodigoPedido` VARCHAR(15) NOT NULL,
  `CodigoProducto` VARCHAR(15) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`CodigoPedido`, `CodigoProducto`),
  INDEX `FK_Producto_Codigo_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `FK_Pedido_Codigo`
    FOREIGN KEY (`CodigoPedido`)
    REFERENCES `mydb`.`Pedido` (`CodigoPedido`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Producto_Codigo`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `mydb`.`Producto` (`Codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
