/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.l2ashdz.sistemaintelaf.ui.tienda;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author asael
 */
public class TiendaView extends javax.swing.JPanel {

    /**
     * Creates new form TiendaView
     */
    public TiendaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opTienda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opTiempos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 44, 52));

        jPanel1.setBackground(new java.awt.Color(48, 54, 64));

        opTienda.setBackground(new java.awt.Color(22, 25, 29));
        opTienda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        opTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opTiendaMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiendas");

        javax.swing.GroupLayout opTiendaLayout = new javax.swing.GroupLayout(opTienda);
        opTienda.setLayout(opTiendaLayout);
        opTiendaLayout.setHorizontalGroup(
            opTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opTiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        opTiendaLayout.setVerticalGroup(
            opTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        opTiempos.setBackground(new java.awt.Color(22, 25, 29));
        opTiempos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        opTiempos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opTiemposMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tiempos");

        javax.swing.GroupLayout opTiemposLayout = new javax.swing.GroupLayout(opTiempos);
        opTiempos.setLayout(opTiemposLayout);
        opTiemposLayout.setHorizontalGroup(
            opTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opTiemposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        opTiemposLayout.setVerticalGroup(
            opTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(opTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opTiempos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 470, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opTiendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opTiendaMousePressed
        setColor(opTienda);
        resetColor(opTiempos);
    }//GEN-LAST:event_opTiendaMousePressed

    private void opTiemposMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opTiemposMousePressed
        setColor(opTiempos);
        resetColor(opTienda);
    }//GEN-LAST:event_opTiemposMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel opTiempos;
    private javax.swing.JPanel opTienda;
    // End of variables declaration//GEN-END:variables

    public void setColor(JPanel panel){
        panel.setBackground(new Color(39,44,52));
    }
    
    public void resetColor (JPanel panel){
       panel.setBackground(new Color(22,25,29));
    }
    
    public JPanel getOpTiempos() {
        return opTiempos;
    }

    public JPanel getOpTienda() {
        return opTienda;
    }

    
}
